// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateTask(arg1:string,arg2:string):Promise<domain.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function Env():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListTasks():Promise<Array<domain.Task>>;

export function ToggleTaskComplete(arg1:string):Promise<domain.Task>;

export function UpdateTaskDetails(arg1:string,arg2:string,arg3:string,arg4:string):Promise<domain.Task>;

export function UpdateTaskDueDate(arg1:string,arg2:string):Promise<domain.Task>;

export function UpdateTaskOrder(arg1:string,arg2:number):Promise<domain.Task>;
